# Generated by Django 3.2.8 on 2021-10-16 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=100, verbose_name='procedimento')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
                ('investigado', models.CharField(max_length=100, verbose_name='investigado')),
                ('vitima', models.CharField(max_length=100, verbose_name='vitima')),
                ('fato', models.CharField(max_length=100, verbose_name='fato')),
                ('autos', models.CharField(blank=True, max_length=100, null=True, verbose_name='autos')),
                ('data_remessa', models.DateField(blank=True, null=True, verbose_name='Data da Remessa')),
                ('data_instauracao', models.DateField(default=None, verbose_name='Data da Instauração')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evento',
            },
        ),
    ]
